namespace Chatter.Models;

public class Group
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public int OwnerId { get; set; }
    public User Owner { get; set; } = null!;
    public bool IsDeactivated { get; set; } = false;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Join code: nullable, generated by owner. Stored as uppercase short string.
    public string? Code { get; set; }
    public DateTime? CodeGeneratedAt { get; set; }

    // Membership navigation
    public ICollection<GroupMembership> Memberships { get; set; } = new List<GroupMembership>();
}
